#cloud-config

# ---- INIT modules ----

users:
  - default
  - name: "{{ vm.ssh_user }}"
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "{{ vm.ssh_public_key }}"
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: "{{ smb.username }}"
device_aliases:
  data: /dev/vdb
disk_setup:
  data:
    table_type: gpt
    layout: true
    overwrite: false
fs_setup:
  - label: data
    filesystem: ext4
    device: data
mounts:
  - [data, "{{ vm.data_disk_mount }}"]
write_files:
  - path: /etc/samba/smb.conf
    permissions: '0644'
    append: false
    content: |
      [global]
      workgroup = WORKGROUP
      server string = Samba Server %h
      interfaces = lo eth0
      bind interfaces only = yes

      log file = /var/log/samba/log.%m
      max log size = 1000
      logging = file
      panic action = /usr/share/samba/panic-action %d

      server role = standalone server
      obey pam restrictions = yes
      unix password sync = yes
      passwd program = /usr/bin/passwd %u
      passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
      pam password change = yes

      map to guest = bad user
      usershare allow guests = yes

      [{{ smb.share }}]
      comment = Kubernetes Share
      path = {{ vm.data_disk_mount }}/{{ smb.share }}
      read only = no
      writable = yes
      browseable = yes
      guest ok = no
      valid users = @{{ smb.username }}
hostname: "{{ vm.name }}"

# ---- CONFIG modules ----

# creates script at config time but runs it in final stage:
runcmd:
  - mkdir -p {{ vm.data_disk_mount }}/{{ smb.share }}
  - printf "{{ smb.password }}\n{{ smb.password }}\n" | smbpasswd -a -s {{ smb.username }}
  - setfacl -R -m "u:{{ smb.username }}:rwx" {{ vm.data_disk_mount }}/{{ smb.share }}
  - ufw allow samba
  - systemctl restart smbd
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

# ---- FINAL MODULES ----

package_upgrade: true
packages:
  - apt-transport-https
  - acl
  - ca-certificates
  - curl
  - gpg
  - net-tools
  - vim
  - samba
  - qemu-guest-agent
