name: Code Quality
on: [push]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # for now reproduce the development folder structure in CI:
      - name: Checkout utilities library
        uses: actions/checkout@v4
        with:
          repository: CrashLoopBackCoffee/mp-deploy-utils
          path: ./mp-deploy-utils
          token: ${{ secrets.PAT_READ_MP_DEPLOY_UTILS }}

      - name: Move utilities library to the right place
        run: mv ./mp-deploy-utils ../deploy-utils

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync

      - name: pyright
        run: uv run pyright --warnings

      - name: ruff check
        run: uv run ruff check

      - name: ruff format
        run: uv run ruff format --check
